#Temps entre chaque phase de partie en minute.

phase-time: 15

#Temps restant au Hinamizawa pour remporter la partie.

rika-death-time: 40

#Taille de bordure au commencement de partie
worldborder: 2000
#Temps Activation de la barriere en seconde
activation-time: 3500
#Taille de bordure minimum apres réduction
worldborder-min: 200
#block par seconde réduit (moitié de block par défaut)
wordborder-time-reduce: 0.5

hanyu:
  dimension:
    spawn-location:
      hanyu:
        x: 10
        y: 10
        z: 10
        world: world
        pitch: 0
      rika:
        x: 15
        y: 15
        z: 15
        world: world
        pitch: 0