#Temps entre chaque phase de partie en minute.
phase-time: 15
#Taille de bordure au commencement de partie
worldborder: 2000
#Temps Activation de la barriere en seconde
activation-time: 3500
#Taille de bordure minimum apres réduction
worldborder-min: 200
#block par seconde réduit (moitié de block par défaut)
wordborder-time-reduce: 0.5

hanyu:
  dimension:
    spawn-location:
      hanyu:
        x: 10
        y: 63
        z: 10
        world: world
        pitch: 0
      rika:
        x: 15
        y: 63
        z: 15
        world: world
        pitch: 0